@startuml
start
:Make ExprVar;
:Create null Expressions
fromExpr and toExpr;
:Create false booleans
justFn and justInverseFn;
if (to == null) then (yes)
:Change justFn to true;
:Change toExpr to new ExprVar;
else (no)
:Add ExprVar with to;
:Change toExpr to Added Expression;
endif
if(from == null) then (yes)
:Change justInverseFn to true;
:Change fromExpr to new ExprVar;
else(no)
:Add ExprVar with from;
:Change fromExpr to Added Expression;
endif
:Call Function;
if (justFn and justInverseFn == false) then (yes)
:Call BijectionFiltered;
elseif(justFn == true) then (yes)
:Call FunctionFiltered;
elseif(justInverseFn == true) then (yes)
:Call InverseFunctionFiltered;
endif
:Create new ArrayList;
:Create new Declaration;
:Add Called Function to Overall Fact;

stop
@enduml