@startuml
start
:Print Title Expr;
:Print Expression Class;
:Print Expression String;
:Print Title expr.findAllFunctions;
while(For All Functions in Expression)
:Print Function;
endwhile
:Print Title expr.getSubnodes;
:Print Expression Sub Nodes;
stop
@enduml