@startuml
start
:Make ExprVar;
:Join from Expr List with ExprVar;
:Join to Expr List with ExprVar;
:Turn from Expr List into one Expr;
:Turn to Expr List into on Expr;
:Call Function Filtered;
:Create ArrayList;
:Create new Declaration;
:Add Function Filtered to Overall Fact;
stop
@enduml