@startuml
start
:Make ExprVar;
if (to == null) then (yes)
:to = ExprVar;
else (no)
endif
if(from == null) then (yes)
:from = ExprVar;
else(no)
endif
:Call FunctionFiltered;
:Create New ArrayList;
:Create New Declaration;
:Add Called Function to Overall Fact;
stop
@enduml