@startuml
start
:Set System Property for graphstream UI;
:Construct SingleGraph //graph//
(API to graphstream);
:Set //graph// to Strict;
:Set //graph// style to Attribute
//stylesheet//;
:Return //graph//;
stop
@enduml
