@startuml
start
:Construct ONode;
:Print //target// Attribute;
if(//target// has 1 Leaving Edge) then (yes)
:Get //target// Edge;
:Get the Edge's Target Node;
if(Target Node has More Than 1 Entering Edge) then (yes)
if(Edge is One Of) then (yes)
:Create int //numOfOneOf//;
if(//numOfOneOf// == 0) then (yes)
:Return New ONode;
stop
else(no)
:Return New ONode;
stop
endif
else(no)
:Return New ONode;
stop
endif
endif
elseif(Target has More Than 1 Leaving Edge) then (yes)
:Create New OListAND;
while(For Each of Leading Edge from Target)
:Get Current Edge;
:Get Edge's Target Node;
:Add Target Node to OListAND;
endwhile
:Return OListAND;
stop
else(no)
:Return new ONode;
endif
:Return null;
stop
@enduml