@startuml
start
:Create New ArrayList, //ls//;
while(For Each IObject in //list//)
:Turn Current IObject to String List;
while(For Each String in IObject)
:Add String to //ls//;
endwhile
endwhile
stop
@enduml