@startuml
start
:Create fieldNames String Array;
:Convert fieldNamesList to Array;
:Instantiate Sig.Field;
:Create Signature;
if (Signature is not null) then (yes)
:Create Sig.Field;
if (Sig.Field length ! = fieldNames length) then (yes)
:Return null;
stop
endif
else(no)
:Return null;
stop
endif
:Return Sig.Field;
stop

@enduml