@startuml
start
:Create Node/ID for //p0, p1, p21start, p211, p212, p213,//
//p21end, p22,// and //pf//;
:Add Edge for //p0p1//, //p1pf//, and //p0p21start//;
:Set Edges oneof Attribute to true;
:Add Edge for //p21startp211, p21startp212, p21startp213,//
//p211p21end, p212p21end, p213p21end, p21endpf, p0p22, p22pf//;
:Set Edges oneof Attribute to true for 
//p21endpf, p0p22, p22pf//;
:Create Node/ID for //p231, p232, p233//;
:Add Edge for //p0p231, p0p232, p0p233, p231pf, p232pf,//
//p233pf//;
:Set Edge Attribute oneof to true for previous Edges;
:Create Node/ID for //p3start, p31, p32, p3end, p33start,//
//p331, p332, p333//;
:Add Edge for //p0p3start, p3startp31, p3startp32, p31p3end,//
//p32p3end, p3endpf, p3startp33start, p33startp331, p33startp332,//
//p33startp333, p331pf, p332pf, p333pf//;
:Set Edges Attribute oneof to true for //p3endpf, p33startp311,//
//p33startp332, p33startp333, p331pf, p332pf, p333pf//;
:Return pfNode;
stop
@enduml