@startuml
start
:Construct Graph2AlloyExpr;
:Get Graph;
:Display Graph;
:Get Happens Before Function;
:Print Happens Before;
:Get Happens Before Inverse Function;
:Print Happens Before Inverse;
stop
@enduml
