@startuml
start
:Create new Array List //hbFunctionFilter//;
while(For Each Key Set in //_map//;)
while(For Each Key in Key Set)
while(For Each Key Value in //_map//)
:Add Current Key String and Value to
//hbFunctionFilter//;
endwhile
endwhile
endwhile
:Return //hbFunctionFilter//;
stop
@enduml