@startuml
start
:Print title All getAllReachableUserDefinedSigs;
while (for all Signatures in Module)
:Print Signature and Attributes;
:Print Children;
:Print Descendents;
:Print Field Declarations;
:Print Fields;
:Print Facts;
endwhile
stop
@enduml