@startuml
start
while (for all Signature Fields)
if(current field == fieldName?) then (yes)
:Return Field;
stop
endif
endwhile
while(sig.parent != null?)
:Print sig.parent;
:Get Field from sig.parent;
if (field != null) then (yes)
:Return Field 
stop
else (no)
:Set sig to sig.parent;
endif
endwhile
:Return null;
stop
@enduml
