@startuml
start
:Set //viz// to null;
:Construct A4Options;
:Set A4Options Parameters;
:COnstruct A4Reporter;
:Set A4Options Solver to SAT4J;
:Execute Command from A4Solution;
:Print Answer Title;
:Print A4Solution Answer;
:Set //previousAns// to A4Solution Answer;
if(A4Solution Answer is Satisfiable) then (yes)
:Print Solution Number;
:Print All Atoms in Answer;
:Print Answer;
:Write Answer to XML;
if(//viz// == null) then (yes)
:Construct VizGUI;
else (no)
:Load XML from//viz//;
endif
:Create AlloyInstance;
:Print A4Solution Answer;
:Print AlloyInstance;
:Print AlloyModel;
:Write AlloyInstance to File;
else(no)
:Print No Satisfied Solution;
endif
stop
@enduml