@startuml
start
:Join p2 with mainSig to create plus;
while(For all Elements in p3s)
:Add current Sig.Field Joined to mainSig with plus;
endwhile
->_mainSig.join(_p1)
plus;
:Create Bijection Filtered;
stop
@enduml