@startuml
start
:Get the A4Solution Answer;
:Increment //solutionCounter//;
if(A4Solution Answer is Satisfiable) then (yes)
:Print Solution Number;
:Print Solution Atoms;
:Write XML;
:Load XML;
:Create AlloyInstance;
:Print Satisfied Answer;
:Print AlloyInstance;
:Print AlloyModel;
:Write AlloyInstance to File;
:Set Attribute //previousAns// to A4Solution;
else(no)
:Print Answer is not Satisfiable;
:Write Answer to XML;
endif
stop
@enduml