@startuml
start
if(//ignoredExpr// contains ExprCall) then (yes)
:Return "";
stop
endif
:Set isRootSig to false;
:Get Name of ExprCall;
:Create String Array from ExprCall Arg Size;
while(For each Arg in String Array)
:Add Arg to String Array;
endwhile
:Create StringBuilder;
:Append ExprCall Name to StringBuilder;
if(ExprCall has Args) then (yes)
:Append String Array to StringBuilder;
endif
:Return StringBuilder toString;
stop
@enduml