@startuml
start
if(//ignoredExprs// Contains Field) then (yes)
:Return //map//;
endif
:Set //isRootSig// to false;
if(//fieldAfterSig//) then (yes)
:Create String //type// from Field
Declaration Expression;
:Create null List of Fields //fs//;
if(//map// Contains //type//) then (yes)
:Set //fs// to //map// at //type//;
else(no)
:Set //fs// to new ArrayList;
:Put //type// and //fs// into //map//;
endif
:Add Field to //fs//;
endif
:Return //map//;
stop
@enduml