@startuml
start
if(//ignoredExpr// contains ExprCall) then (yes)
:Return "";
stop
endif
:Set //isRootSig// to false;
if(//fieldAfterSig//)
:Create StringBuilder;
:Append Field Label With Slash Removed
and Field Declaration Expression
to StringBuilder;
:Return StringBuilder toString;
stop
endif
:Return Field Label;
stop
@enduml