@startuml
start
:Get Source Field Type;
:Get Target Field Type;
:Create Source Bijection Filtered;
:Create Target Bijection Filtered;
:Create Sub Setting Item Rule;
:Create Source is Before Target Field;
stop
@enduml